
package com.gmq.psp.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-20T09:18:10.473+01:00
 * Generated source version: 3.3.5
 *
 */

public class HelloWorldPSP_HelloWorldPSPSOAP_Server{

    protected HelloWorldPSP_HelloWorldPSPSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldPSPSOAPImpl();
        String address = "http://localhost:8080/helloWorldPSP/services";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new HelloWorldPSP_HelloWorldPSPSOAP_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
