package com.gmq.psp.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-14T00:16:57.665+01:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "helloWorldPSP",
                  wsdlLocation = "file:/Users/Raul.Camarero/Documents/PSP/T4-GeneracionServiciosEnRed/Ejercicios/helloWorldPSP/helloWorldPSP.wsdl",
                  targetNamespace = "http://www.example.org/helloWorldPSP/")
public class HelloWorldPSP_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/helloWorldPSP/", "helloWorldPSP");
    public final static QName HelloWorldPSPSOAP = new QName("http://www.example.org/helloWorldPSP/", "helloWorldPSPSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Raul.Camarero/Documents/PSP/T4-GeneracionServiciosEnRed/Ejercicios/helloWorldPSP/helloWorldPSP.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldPSP_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/Raul.Camarero/Documents/PSP/T4-GeneracionServiciosEnRed/Ejercicios/helloWorldPSP/helloWorldPSP.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldPSP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldPSP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldPSP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWorldPSP_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldPSP_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldPSP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWorldPSP
     */
    @WebEndpoint(name = "helloWorldPSPSOAP")
    public HelloWorldPSP getHelloWorldPSPSOAP() {
        return super.getPort(HelloWorldPSPSOAP, HelloWorldPSP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldPSP
     */
    @WebEndpoint(name = "helloWorldPSPSOAP")
    public HelloWorldPSP getHelloWorldPSPSOAP(WebServiceFeature... features) {
        return super.getPort(HelloWorldPSPSOAP, HelloWorldPSP.class, features);
    }

}
